import { MMU } from '../mmu.js';
import type { Registers } from './cpu.js';
import type { Opcode } from './opcode-table.js';
import { createRlcB } from './instructions/cb/rlc-b.js';
import { createRlcC } from './instructions/cb/rlc-c.js';
import { createRlcD } from './instructions/cb/rlc-d.js';
import { createRlcE } from './instructions/cb/rlc-e.js';
import { createRlcH } from './instructions/cb/rlc-h.js';
import { createRlcL } from './instructions/cb/rlc-l.js';
import { createRlcHL } from './instructions/cb/rlc-hl.js';
import { createRlcA } from './instructions/cb/rlc-a.js';
import { createRrcB } from './instructions/cb/rrc-b.js';
import { createRrcC } from './instructions/cb/rrc-c.js';
import { createRrcD } from './instructions/cb/rrc-d.js';
import { createRrcE } from './instructions/cb/rrc-e.js';
import { createRrcH } from './instructions/cb/rrc-h.js';
import { createRrcL } from './instructions/cb/rrc-l.js';
import { createRrcHL } from './instructions/cb/rrc-hl.js';
import { createRrcA } from './instructions/cb/rrc-a.js';
import { createRlB } from './instructions/cb/rl-b.js';
import { createRlC } from './instructions/cb/rl-c.js';
import { createRlD } from './instructions/cb/rl-d.js';
import { createRlE } from './instructions/cb/rl-e.js';
import { createRlH } from './instructions/cb/rl-h.js';
import { createRlL } from './instructions/cb/rl-l.js';
import { createRlHL } from './instructions/cb/rl-hl.js';
import { createRlA } from './instructions/cb/rl-a.js';
import { createRrB } from './instructions/cb/rr-b.js';
import { createRrC } from './instructions/cb/rr-c.js';
import { createRrD } from './instructions/cb/rr-d.js';
import { createRrE } from './instructions/cb/rr-e.js';
import { createRrH } from './instructions/cb/rr-h.js';
import { createRrL } from './instructions/cb/rr-l.js';
import { createRrHL } from './instructions/cb/rr-hl.js';
import { createRrA } from './instructions/cb/rr-a.js';
import { createSlaB } from './instructions/cb/sla-b.js';
import { createSlaC } from './instructions/cb/sla-c.js';
import { createSlaD } from './instructions/cb/sla-d.js';
import { createSlaE } from './instructions/cb/sla-e.js';
import { createSlaH } from './instructions/cb/sla-h.js';
import { createSlaL } from './instructions/cb/sla-l.js';
import { createSlaHL } from './instructions/cb/sla-hl.js';
import { createSlaA } from './instructions/cb/sla-a.js';
import { createSraB } from './instructions/cb/sra-b.js';
import { createSraC } from './instructions/cb/sra-c.js';
import { createSraD } from './instructions/cb/sra-d.js';
import { createSraE } from './instructions/cb/sra-e.js';
import { createSraH } from './instructions/cb/sra-h.js';
import { createSraL } from './instructions/cb/sra-l.js';
import { createSraHL } from './instructions/cb/sra-hl.js';
import { createSraA } from './instructions/cb/sra-a.js';
import { createSwapB } from './instructions/cb/swap-b.js';
import { createSwapC } from './instructions/cb/swap-c.js';
import { createSwapD } from './instructions/cb/swap-d.js';
import { createSwapE } from './instructions/cb/swap-e.js';
import { createSwapH } from './instructions/cb/swap-h.js';
import { createSwapL } from './instructions/cb/swap-l.js';
import { createSwapHL } from './instructions/cb/swap-hl.js';
import { createSwapA } from './instructions/cb/swap-a.js';
import { createSrlB } from './instructions/cb/srl-b.js';
import { createSrlC } from './instructions/cb/srl-c.js';
import { createSrlD } from './instructions/cb/srl-d.js';
import { createSrlE } from './instructions/cb/srl-e.js';
import { createSrlH } from './instructions/cb/srl-h.js';
import { createSrlL } from './instructions/cb/srl-l.js';
import { createSrlHL } from './instructions/cb/srl-hl.js';
import { createSrlA } from './instructions/cb/srl-a.js';
import { createBit0B } from './instructions/cb/bit-0-b.js';
import { createBit0C } from './instructions/cb/bit-0-c.js';
import { createBit0D } from './instructions/cb/bit-0-d.js';
import { createBit0E } from './instructions/cb/bit-0-e.js';
import { createBit0H } from './instructions/cb/bit-0-h.js';
import { createBit0L } from './instructions/cb/bit-0-l.js';
import { createBit0HL } from './instructions/cb/bit-0-hl.js';
import { createBit0A } from './instructions/cb/bit-0-a.js';
import { createBit1B } from './instructions/cb/bit-1-b.js';
import { createBit1C } from './instructions/cb/bit-1-c.js';
import { createBit1D } from './instructions/cb/bit-1-d.js';
import { createBit1E } from './instructions/cb/bit-1-e.js';
import { createBit1H } from './instructions/cb/bit-1-h.js';
import { createBit1L } from './instructions/cb/bit-1-l.js';
import { createBit1HL } from './instructions/cb/bit-1-hl.js';
import { createBit1A } from './instructions/cb/bit-1-a.js';
import { createBit2B } from './instructions/cb/bit-2-b.js';
import { createBit2C } from './instructions/cb/bit-2-c.js';
import { createBit2D } from './instructions/cb/bit-2-d.js';
import { createBit2E } from './instructions/cb/bit-2-e.js';
import { createBit2H } from './instructions/cb/bit-2-h.js';
import { createBit2L } from './instructions/cb/bit-2-l.js';
import { createBit2HL } from './instructions/cb/bit-2-hl.js';
import { createBit2A } from './instructions/cb/bit-2-a.js';
import { createBit3B } from './instructions/cb/bit-3-b.js';
import { createBit3C } from './instructions/cb/bit-3-c.js';
import { createBit3D } from './instructions/cb/bit-3-d.js';
import { createBit3E } from './instructions/cb/bit-3-e.js';
import { createBit3H } from './instructions/cb/bit-3-h.js';
import { createBit3L } from './instructions/cb/bit-3-l.js';
import { createBit3HL } from './instructions/cb/bit-3-hl.js';
import { createBit3A } from './instructions/cb/bit-3-a.js';
import { createBit4B } from './instructions/cb/bit-4-b.js';
import { createBit4C } from './instructions/cb/bit-4-c.js';
import { createBit4D } from './instructions/cb/bit-4-d.js';
import { createBit4E } from './instructions/cb/bit-4-e.js';
import { createBit4H } from './instructions/cb/bit-4-h.js';
import { createBit4L } from './instructions/cb/bit-4-l.js';
import { createBit4HL } from './instructions/cb/bit-4-hl.js';
import { createBit4A } from './instructions/cb/bit-4-a.js';
import { createBit5B } from './instructions/cb/bit-5-b.js';
import { createBit5C } from './instructions/cb/bit-5-c.js';
import { createBit5D } from './instructions/cb/bit-5-d.js';
import { createBit5E } from './instructions/cb/bit-5-e.js';
import { createBit5H } from './instructions/cb/bit-5-h.js';
import { createBit5L } from './instructions/cb/bit-5-l.js';
import { createBit5HL } from './instructions/cb/bit-5-hl.js';
import { createBit5A } from './instructions/cb/bit-5-a.js';
import { createBit6B } from './instructions/cb/bit-6-b.js';
import { createBit6C } from './instructions/cb/bit-6-c.js';
import { createBit6D } from './instructions/cb/bit-6-d.js';
import { createBit6E } from './instructions/cb/bit-6-e.js';
import { createBit6H } from './instructions/cb/bit-6-h.js';
import { createBit6L } from './instructions/cb/bit-6-l.js';
import { createBit6HL } from './instructions/cb/bit-6-hl.js';
import { createBit6A } from './instructions/cb/bit-6-a.js';
import { createBit7B } from './instructions/cb/bit-7-b.js';
import { createBit7C } from './instructions/cb/bit-7-c.js';
import { createBit7D } from './instructions/cb/bit-7-d.js';
import { createBit7E } from './instructions/cb/bit-7-e.js';
import { createBit7H } from './instructions/cb/bit-7-h.js';
import { createBit7L } from './instructions/cb/bit-7-l.js';
import { createBit7HL } from './instructions/cb/bit-7-hl.js';
import { createBit7A } from './instructions/cb/bit-7-a.js';
import { createRes0B } from './instructions/cb/res-0-b.js';
import { createRes0C } from './instructions/cb/res-0-c.js';
import { createRes0D } from './instructions/cb/res-0-d.js';
import { createRes0E } from './instructions/cb/res-0-e.js';
import { createRes0H } from './instructions/cb/res-0-h.js';
import { createRes0L } from './instructions/cb/res-0-l.js';
import { createRes0HL } from './instructions/cb/res-0-hl.js';
import { createRes0A } from './instructions/cb/res-0-a.js';
import { createRes1B } from './instructions/cb/res-1-b.js';
import { createRes1C } from './instructions/cb/res-1-c.js';
import { createRes1D } from './instructions/cb/res-1-d.js';
import { createRes1E } from './instructions/cb/res-1-e.js';
import { createRes1H } from './instructions/cb/res-1-h.js';
import { createRes1L } from './instructions/cb/res-1-l.js';
import { createRes1HL } from './instructions/cb/res-1-hl.js';
import { createRes1A } from './instructions/cb/res-1-a.js';
import { createRes2B } from './instructions/cb/res-2-b.js';
import { createRes2C } from './instructions/cb/res-2-c.js';
import { createRes2D } from './instructions/cb/res-2-d.js';
import { createRes2E } from './instructions/cb/res-2-e.js';
import { createRes2H } from './instructions/cb/res-2-h.js';
import { createRes2L } from './instructions/cb/res-2-l.js';
import { createRes2HL } from './instructions/cb/res-2-hl.js';
import { createRes2A } from './instructions/cb/res-2-a.js';
import { createRes3B } from './instructions/cb/res-3-b.js';
import { createRes3C } from './instructions/cb/res-3-c.js';
import { createRes3D } from './instructions/cb/res-3-d.js';
import { createRes3E } from './instructions/cb/res-3-e.js';
import { createRes3H } from './instructions/cb/res-3-h.js';
import { createRes3L } from './instructions/cb/res-3-l.js';
import { createRes3HL } from './instructions/cb/res-3-hl.js';
import { createRes3A } from './instructions/cb/res-3-a.js';
import { createRes4B } from './instructions/cb/res-4-b.js';
import { createRes4C } from './instructions/cb/res-4-c.js';
import { createRes4D } from './instructions/cb/res-4-d.js';
import { createRes4E } from './instructions/cb/res-4-e.js';
import { createRes4H } from './instructions/cb/res-4-h.js';
import { createRes4L } from './instructions/cb/res-4-l.js';
import { createRes4HL } from './instructions/cb/res-4-hl.js';
import { createRes4A } from './instructions/cb/res-4-a.js';
import { createRes5B } from './instructions/cb/res-5-b.js';
import { createRes5C } from './instructions/cb/res-5-c.js';
import { createRes5D } from './instructions/cb/res-5-d.js';
import { createRes5E } from './instructions/cb/res-5-e.js';
import { createRes5H } from './instructions/cb/res-5-h.js';
import { createRes5L } from './instructions/cb/res-5-l.js';
import { createRes5HL } from './instructions/cb/res-5-hl.js';
import { createRes5A } from './instructions/cb/res-5-a.js';
import { createRes6B } from './instructions/cb/res-6-b.js';
import { createRes6C } from './instructions/cb/res-6-c.js';
import { createRes6D } from './instructions/cb/res-6-d.js';
import { createRes6E } from './instructions/cb/res-6-e.js';
import { createRes6H } from './instructions/cb/res-6-h.js';
import { createRes6L } from './instructions/cb/res-6-l.js';
import { createRes6HL } from './instructions/cb/res-6-hl.js';
import { createRes6A } from './instructions/cb/res-6-a.js';
import { createRes7B } from './instructions/cb/res-7-b.js';
import { createRes7C } from './instructions/cb/res-7-c.js';
import { createRes7D } from './instructions/cb/res-7-d.js';
import { createRes7E } from './instructions/cb/res-7-e.js';
import { createRes7H } from './instructions/cb/res-7-h.js';
import { createRes7L } from './instructions/cb/res-7-l.js';
import { createRes7HL } from './instructions/cb/res-7-hl.js';
import { createRes7A } from './instructions/cb/res-7-a.js';
import { createSet0B } from './instructions/cb/set-0-b.js';
import { createSet0C } from './instructions/cb/set-0-c.js';
import { createSet0D } from './instructions/cb/set-0-d.js';
import { createSet0E } from './instructions/cb/set-0-e.js';
import { createSet0H } from './instructions/cb/set-0-h.js';
import { createSet0L } from './instructions/cb/set-0-l.js';
import { createSet0HL } from './instructions/cb/set-0-hl.js';
import { createSet0A } from './instructions/cb/set-0-a.js';
import { createSet1B } from './instructions/cb/set-1-b.js';
import { createSet1C } from './instructions/cb/set-1-c.js';
import { createSet1D } from './instructions/cb/set-1-d.js';
import { createSet1E } from './instructions/cb/set-1-e.js';
import { createSet1H } from './instructions/cb/set-1-h.js';
import { createSet1L } from './instructions/cb/set-1-l.js';
import { createSet1HL } from './instructions/cb/set-1-hl.js';
import { createSet1A } from './instructions/cb/set-1-a.js';
import { createSet2B } from './instructions/cb/set-2-b.js';
import { createSet2C } from './instructions/cb/set-2-c.js';
import { createSet2D } from './instructions/cb/set-2-d.js';
import { createSet2E } from './instructions/cb/set-2-e.js';
import { createSet2H } from './instructions/cb/set-2-h.js';
import { createSet2L } from './instructions/cb/set-2-l.js';
import { createSet2HL } from './instructions/cb/set-2-hl.js';
import { createSet2A } from './instructions/cb/set-2-a.js';
import { createSet3B } from './instructions/cb/set-3-b.js';
import { createSet3C } from './instructions/cb/set-3-c.js';
import { createSet3D } from './instructions/cb/set-3-d.js';
import { createSet3E } from './instructions/cb/set-3-e.js';
import { createSet3H } from './instructions/cb/set-3-h.js';
import { createSet3L } from './instructions/cb/set-3-l.js';
import { createSet3HL } from './instructions/cb/set-3-hl.js';
import { createSet3A } from './instructions/cb/set-3-a.js';
import { createSet4B } from './instructions/cb/set-4-b.js';
import { createSet4C } from './instructions/cb/set-4-c.js';
import { createSet4D } from './instructions/cb/set-4-d.js';
import { createSet4E } from './instructions/cb/set-4-e.js';
import { createSet4H } from './instructions/cb/set-4-h.js';
import { createSet4L } from './instructions/cb/set-4-l.js';
import { createSet4HL } from './instructions/cb/set-4-hl.js';
import { createSet4A } from './instructions/cb/set-4-a.js';
import { createSet5B } from './instructions/cb/set-5-b.js';
import { createSet5C } from './instructions/cb/set-5-c.js';
import { createSet5D } from './instructions/cb/set-5-d.js';
import { createSet5E } from './instructions/cb/set-5-e.js';
import { createSet5H } from './instructions/cb/set-5-h.js';
import { createSet5L } from './instructions/cb/set-5-l.js';
import { createSet5HL } from './instructions/cb/set-5-hl.js';
import { createSet5A } from './instructions/cb/set-5-a.js';
import { createSet6B } from './instructions/cb/set-6-b.js';
import { createSet6C } from './instructions/cb/set-6-c.js';
import { createSet6D } from './instructions/cb/set-6-d.js';
import { createSet6E } from './instructions/cb/set-6-e.js';
import { createSet6H } from './instructions/cb/set-6-h.js';
import { createSet6L } from './instructions/cb/set-6-l.js';
import { createSet6HL } from './instructions/cb/set-6-hl.js';
import { createSet6A } from './instructions/cb/set-6-a.js';
import { createSet7B } from './instructions/cb/set-7-b.js';
import { createSet7C } from './instructions/cb/set-7-c.js';
import { createSet7D } from './instructions/cb/set-7-d.js';
import { createSet7E } from './instructions/cb/set-7-e.js';
import { createSet7H } from './instructions/cb/set-7-h.js';
import { createSet7L } from './instructions/cb/set-7-l.js';
import { createSet7HL } from './instructions/cb/set-7-hl.js';
import { createSet7A } from './instructions/cb/set-7-a.js';

type CbOpcodeTableDependencies = {
  mmu: MMU;
  registers: Registers;
};

const createCbOpcodeTable = ({
  mmu,
  registers,
}: CbOpcodeTableDependencies): Array<Opcode | undefined> => {
  const cbOpcodes: Array<Opcode | undefined> = [];

  cbOpcodes[0x00] = createRlcB({ registers });
  cbOpcodes[0x01] = createRlcC({ registers });
  cbOpcodes[0x02] = createRlcD({ registers });
  cbOpcodes[0x03] = createRlcE({ registers });
  cbOpcodes[0x04] = createRlcH({ registers });
  cbOpcodes[0x05] = createRlcL({ registers });
  cbOpcodes[0x06] = createRlcHL({ mmu, registers });
  cbOpcodes[0x07] = createRlcA({ registers });
  cbOpcodes[0x08] = createRrcB({ registers });
  cbOpcodes[0x09] = createRrcC({ registers });
  cbOpcodes[0x0a] = createRrcD({ registers });
  cbOpcodes[0x0b] = createRrcE({ registers });
  cbOpcodes[0x0c] = createRrcH({ registers });
  cbOpcodes[0x0d] = createRrcL({ registers });
  cbOpcodes[0x0e] = createRrcHL({ mmu, registers });
  cbOpcodes[0x0f] = createRrcA({ registers });
  cbOpcodes[0x10] = createRlB({ registers });
  cbOpcodes[0x11] = createRlC({ registers });
  cbOpcodes[0x12] = createRlD({ registers });
  cbOpcodes[0x13] = createRlE({ registers });
  cbOpcodes[0x14] = createRlH({ registers });
  cbOpcodes[0x15] = createRlL({ registers });
  cbOpcodes[0x16] = createRlHL({ mmu, registers });
  cbOpcodes[0x17] = createRlA({ registers });
  cbOpcodes[0x18] = createRrB({ registers });
  cbOpcodes[0x19] = createRrC({ registers });
  cbOpcodes[0x1a] = createRrD({ registers });
  cbOpcodes[0x1b] = createRrE({ registers });
  cbOpcodes[0x1c] = createRrH({ registers });
  cbOpcodes[0x1d] = createRrL({ registers });
  cbOpcodes[0x1e] = createRrHL({ mmu, registers });
  cbOpcodes[0x1f] = createRrA({ registers });
  cbOpcodes[0x20] = createSlaB({ registers });
  cbOpcodes[0x21] = createSlaC({ registers });
  cbOpcodes[0x22] = createSlaD({ registers });
  cbOpcodes[0x23] = createSlaE({ registers });
  cbOpcodes[0x24] = createSlaH({ registers });
  cbOpcodes[0x25] = createSlaL({ registers });
  cbOpcodes[0x26] = createSlaHL({ mmu, registers });
  cbOpcodes[0x27] = createSlaA({ registers });
  cbOpcodes[0x28] = createSraB({ registers });
  cbOpcodes[0x29] = createSraC({ registers });
  cbOpcodes[0x2a] = createSraD({ registers });
  cbOpcodes[0x2b] = createSraE({ registers });
  cbOpcodes[0x2c] = createSraH({ registers });
  cbOpcodes[0x2d] = createSraL({ registers });
  cbOpcodes[0x2e] = createSraHL({ mmu, registers });
  cbOpcodes[0x2f] = createSraA({ registers });
  cbOpcodes[0x30] = createSwapB({ registers });
  cbOpcodes[0x31] = createSwapC({ registers });
  cbOpcodes[0x32] = createSwapD({ registers });
  cbOpcodes[0x33] = createSwapE({ registers });
  cbOpcodes[0x34] = createSwapH({ registers });
  cbOpcodes[0x35] = createSwapL({ registers });
  cbOpcodes[0x36] = createSwapHL({ mmu, registers });
  cbOpcodes[0x37] = createSwapA({ registers });
  cbOpcodes[0x38] = createSrlB({ registers });
  cbOpcodes[0x39] = createSrlC({ registers });
  cbOpcodes[0x3a] = createSrlD({ registers });
  cbOpcodes[0x3b] = createSrlE({ registers });
  cbOpcodes[0x3c] = createSrlH({ registers });
  cbOpcodes[0x3d] = createSrlL({ registers });
  cbOpcodes[0x3e] = createSrlHL({ mmu, registers });
  cbOpcodes[0x3f] = createSrlA({ registers });
  cbOpcodes[0x40] = createBit0B({ registers });
  cbOpcodes[0x41] = createBit0C({ registers });
  cbOpcodes[0x42] = createBit0D({ registers });
  cbOpcodes[0x43] = createBit0E({ registers });
  cbOpcodes[0x44] = createBit0H({ registers });
  cbOpcodes[0x45] = createBit0L({ registers });
  cbOpcodes[0x46] = createBit0HL({ mmu, registers });
  cbOpcodes[0x47] = createBit0A({ registers });
  cbOpcodes[0x48] = createBit1B({ registers });
  cbOpcodes[0x49] = createBit1C({ registers });
  cbOpcodes[0x4a] = createBit1D({ registers });
  cbOpcodes[0x4b] = createBit1E({ registers });
  cbOpcodes[0x4c] = createBit1H({ registers });
  cbOpcodes[0x4d] = createBit1L({ registers });
  cbOpcodes[0x4e] = createBit1HL({ mmu, registers });
  cbOpcodes[0x4f] = createBit1A({ registers });
  cbOpcodes[0x50] = createBit2B({ registers });
  cbOpcodes[0x51] = createBit2C({ registers });
  cbOpcodes[0x52] = createBit2D({ registers });
  cbOpcodes[0x53] = createBit2E({ registers });
  cbOpcodes[0x54] = createBit2H({ registers });
  cbOpcodes[0x55] = createBit2L({ registers });
  cbOpcodes[0x56] = createBit2HL({ mmu, registers });
  cbOpcodes[0x57] = createBit2A({ registers });
  cbOpcodes[0x58] = createBit3B({ registers });
  cbOpcodes[0x59] = createBit3C({ registers });
  cbOpcodes[0x5a] = createBit3D({ registers });
  cbOpcodes[0x5b] = createBit3E({ registers });
  cbOpcodes[0x5c] = createBit3H({ registers });
  cbOpcodes[0x5d] = createBit3L({ registers });
  cbOpcodes[0x5e] = createBit3HL({ mmu, registers });
  cbOpcodes[0x5f] = createBit3A({ registers });
  cbOpcodes[0x60] = createBit4B({ registers });
  cbOpcodes[0x61] = createBit4C({ registers });
  cbOpcodes[0x62] = createBit4D({ registers });
  cbOpcodes[0x63] = createBit4E({ registers });
  cbOpcodes[0x64] = createBit4H({ registers });
  cbOpcodes[0x65] = createBit4L({ registers });
  cbOpcodes[0x66] = createBit4HL({ mmu, registers });
  cbOpcodes[0x67] = createBit4A({ registers });
  cbOpcodes[0x68] = createBit5B({ registers });
  cbOpcodes[0x69] = createBit5C({ registers });
  cbOpcodes[0x6a] = createBit5D({ registers });
  cbOpcodes[0x6b] = createBit5E({ registers });
  cbOpcodes[0x6c] = createBit5H({ registers });
  cbOpcodes[0x6d] = createBit5L({ registers });
  cbOpcodes[0x6e] = createBit5HL({ mmu, registers });
  cbOpcodes[0x6f] = createBit5A({ registers });
  cbOpcodes[0x70] = createBit6B({ registers });
  cbOpcodes[0x71] = createBit6C({ registers });
  cbOpcodes[0x72] = createBit6D({ registers });
  cbOpcodes[0x73] = createBit6E({ registers });
  cbOpcodes[0x74] = createBit6H({ registers });
  cbOpcodes[0x75] = createBit6L({ registers });
  cbOpcodes[0x76] = createBit6HL({ mmu, registers });
  cbOpcodes[0x77] = createBit6A({ registers });
  cbOpcodes[0x78] = createBit7B({ registers });
  cbOpcodes[0x79] = createBit7C({ registers });
  cbOpcodes[0x7a] = createBit7D({ registers });
  cbOpcodes[0x7b] = createBit7E({ registers });
  cbOpcodes[0x7c] = createBit7H({ registers });
  cbOpcodes[0x7d] = createBit7L({ registers });
  cbOpcodes[0x7e] = createBit7HL({ mmu, registers });
  cbOpcodes[0x7f] = createBit7A({ registers });
  cbOpcodes[0x80] = createRes0B({ registers });
  cbOpcodes[0x81] = createRes0C({ registers });
  cbOpcodes[0x82] = createRes0D({ registers });
  cbOpcodes[0x83] = createRes0E({ registers });
  cbOpcodes[0x84] = createRes0H({ registers });
  cbOpcodes[0x85] = createRes0L({ registers });
  cbOpcodes[0x86] = createRes0HL({ mmu, registers });
  cbOpcodes[0x87] = createRes0A({ registers });
  cbOpcodes[0x88] = createRes1B({ registers });
  cbOpcodes[0x89] = createRes1C({ registers });
  cbOpcodes[0x8a] = createRes1D({ registers });
  cbOpcodes[0x8b] = createRes1E({ registers });
  cbOpcodes[0x8c] = createRes1H({ registers });
  cbOpcodes[0x8d] = createRes1L({ registers });
  cbOpcodes[0x8e] = createRes1HL({ mmu, registers });
  cbOpcodes[0x8f] = createRes1A({ registers });
  cbOpcodes[0x90] = createRes2B({ registers });
  cbOpcodes[0x91] = createRes2C({ registers });
  cbOpcodes[0x92] = createRes2D({ registers });
  cbOpcodes[0x93] = createRes2E({ registers });
  cbOpcodes[0x94] = createRes2H({ registers });
  cbOpcodes[0x95] = createRes2L({ registers });
  cbOpcodes[0x96] = createRes2HL({ mmu, registers });
  cbOpcodes[0x97] = createRes2A({ registers });
  cbOpcodes[0x98] = createRes3B({ registers });
  cbOpcodes[0x99] = createRes3C({ registers });
  cbOpcodes[0x9a] = createRes3D({ registers });
  cbOpcodes[0x9b] = createRes3E({ registers });
  cbOpcodes[0x9c] = createRes3H({ registers });
  cbOpcodes[0x9d] = createRes3L({ registers });
  cbOpcodes[0x9e] = createRes3HL({ mmu, registers });
  cbOpcodes[0x9f] = createRes3A({ registers });
  cbOpcodes[0xa0] = createRes4B({ registers });
  cbOpcodes[0xa1] = createRes4C({ registers });
  cbOpcodes[0xa2] = createRes4D({ registers });
  cbOpcodes[0xa3] = createRes4E({ registers });
  cbOpcodes[0xa4] = createRes4H({ registers });
  cbOpcodes[0xa5] = createRes4L({ registers });
  cbOpcodes[0xa6] = createRes4HL({ mmu, registers });
  cbOpcodes[0xa7] = createRes4A({ registers });
  cbOpcodes[0xa8] = createRes5B({ registers });
  cbOpcodes[0xa9] = createRes5C({ registers });
  cbOpcodes[0xaa] = createRes5D({ registers });
  cbOpcodes[0xab] = createRes5E({ registers });
  cbOpcodes[0xac] = createRes5H({ registers });
  cbOpcodes[0xad] = createRes5L({ registers });
  cbOpcodes[0xae] = createRes5HL({ mmu, registers });
  cbOpcodes[0xaf] = createRes5A({ registers });
  cbOpcodes[0xb0] = createRes6B({ registers });
  cbOpcodes[0xb1] = createRes6C({ registers });
  cbOpcodes[0xb2] = createRes6D({ registers });
  cbOpcodes[0xb3] = createRes6E({ registers });
  cbOpcodes[0xb4] = createRes6H({ registers });
  cbOpcodes[0xb5] = createRes6L({ registers });
  cbOpcodes[0xb6] = createRes6HL({ mmu, registers });
  cbOpcodes[0xb7] = createRes6A({ registers });
  cbOpcodes[0xb8] = createRes7B({ registers });
  cbOpcodes[0xb9] = createRes7C({ registers });
  cbOpcodes[0xba] = createRes7D({ registers });
  cbOpcodes[0xbb] = createRes7E({ registers });
  cbOpcodes[0xbc] = createRes7H({ registers });
  cbOpcodes[0xbd] = createRes7L({ registers });
  cbOpcodes[0xbe] = createRes7HL({ mmu, registers });
  cbOpcodes[0xbf] = createRes7A({ registers });
  cbOpcodes[0xc0] = createSet0B({ registers });
  cbOpcodes[0xc1] = createSet0C({ registers });
  cbOpcodes[0xc2] = createSet0D({ registers });
  cbOpcodes[0xc3] = createSet0E({ registers });
  cbOpcodes[0xc4] = createSet0H({ registers });
  cbOpcodes[0xc5] = createSet0L({ registers });
  cbOpcodes[0xc6] = createSet0HL({ mmu, registers });
  cbOpcodes[0xc7] = createSet0A({ registers });
  cbOpcodes[0xc8] = createSet1B({ registers });
  cbOpcodes[0xc9] = createSet1C({ registers });
  cbOpcodes[0xca] = createSet1D({ registers });
  cbOpcodes[0xcb] = createSet1E({ registers });
  cbOpcodes[0xcc] = createSet1H({ registers });
  cbOpcodes[0xcd] = createSet1L({ registers });
  cbOpcodes[0xce] = createSet1HL({ mmu, registers });
  cbOpcodes[0xcf] = createSet1A({ registers });
  cbOpcodes[0xd0] = createSet2B({ registers });
  cbOpcodes[0xd1] = createSet2C({ registers });
  cbOpcodes[0xd2] = createSet2D({ registers });
  cbOpcodes[0xd3] = createSet2E({ registers });
  cbOpcodes[0xd4] = createSet2H({ registers });
  cbOpcodes[0xd5] = createSet2L({ registers });
  cbOpcodes[0xd6] = createSet2HL({ mmu, registers });
  cbOpcodes[0xd7] = createSet2A({ registers });
  cbOpcodes[0xd8] = createSet3B({ registers });
  cbOpcodes[0xd9] = createSet3C({ registers });
  cbOpcodes[0xda] = createSet3D({ registers });
  cbOpcodes[0xdb] = createSet3E({ registers });
  cbOpcodes[0xdc] = createSet3H({ registers });
  cbOpcodes[0xdd] = createSet3L({ registers });
  cbOpcodes[0xde] = createSet3HL({ mmu, registers });
  cbOpcodes[0xdf] = createSet3A({ registers });
  cbOpcodes[0xe0] = createSet4B({ registers });
  cbOpcodes[0xe1] = createSet4C({ registers });
  cbOpcodes[0xe2] = createSet4D({ registers });
  cbOpcodes[0xe3] = createSet4E({ registers });
  cbOpcodes[0xe4] = createSet4H({ registers });
  cbOpcodes[0xe5] = createSet4L({ registers });
  cbOpcodes[0xe6] = createSet4HL({ mmu, registers });
  cbOpcodes[0xe7] = createSet4A({ registers });
  cbOpcodes[0xe8] = createSet5B({ registers });
  cbOpcodes[0xe9] = createSet5C({ registers });
  cbOpcodes[0xea] = createSet5D({ registers });
  cbOpcodes[0xeb] = createSet5E({ registers });
  cbOpcodes[0xec] = createSet5H({ registers });
  cbOpcodes[0xed] = createSet5L({ registers });
  cbOpcodes[0xee] = createSet5HL({ mmu, registers });
  cbOpcodes[0xef] = createSet5A({ registers });
  cbOpcodes[0xf0] = createSet6B({ registers });
  cbOpcodes[0xf1] = createSet6C({ registers });
  cbOpcodes[0xf2] = createSet6D({ registers });
  cbOpcodes[0xf3] = createSet6E({ registers });
  cbOpcodes[0xf4] = createSet6H({ registers });
  cbOpcodes[0xf5] = createSet6L({ registers });
  cbOpcodes[0xf6] = createSet6HL({ mmu, registers });
  cbOpcodes[0xf7] = createSet6A({ registers });
  cbOpcodes[0xf8] = createSet7B({ registers });
  cbOpcodes[0xf9] = createSet7C({ registers });
  cbOpcodes[0xfa] = createSet7D({ registers });
  cbOpcodes[0xfb] = createSet7E({ registers });
  cbOpcodes[0xfc] = createSet7H({ registers });
  cbOpcodes[0xfd] = createSet7L({ registers });
  cbOpcodes[0xfe] = createSet7HL({ mmu, registers });
  cbOpcodes[0xff] = createSet7A({ registers });

  return cbOpcodes;
};

export { createCbOpcodeTable };
