import { MMU } from '../mmu.js';
import type { Registers } from './cpu.js';
import { createIncB } from './instructions/arithmetic/inc-b.js';
import { createIncC } from './instructions/arithmetic/inc-c.js';
import { createIncD } from './instructions/arithmetic/inc-d.js';
import { createIncE } from './instructions/arithmetic/inc-e.js';
import { createIncH } from './instructions/arithmetic/inc-h.js';
import { createIncL } from './instructions/arithmetic/inc-l.js';
import { createIncA } from './instructions/arithmetic/inc-a.js';
import { createIncHLIndirect } from './instructions/arithmetic/inc-hl-indirect.js';
import { createNop } from './instructions/control/nop.js';
import { createLdBD8 } from './instructions/load/ld-b-d8.js';
import { createDecB } from './instructions/arithmetic/dec-b.js';
import { createDecC } from './instructions/arithmetic/dec-c.js';
import { createDecD } from './instructions/arithmetic/dec-d.js';
import { createDecE } from './instructions/arithmetic/dec-e.js';
import { createDecH } from './instructions/arithmetic/dec-h.js';
import { createDecL } from './instructions/arithmetic/dec-l.js';
import { createDecA } from './instructions/arithmetic/dec-a.js';
import { createDecHL } from './instructions/arithmetic/dec-hl.js';
import { createLdCD8 } from './instructions/load/ld-c-d8.js';
import { createLdDD8 } from './instructions/load/ld-d-d8.js';
import { createLdHLD8 } from './instructions/load/ld-hl-d8.js';
import { createLdED8 } from './instructions/load/ld-e-d8.js';
import { createRet } from './instructions/control/ret.js';
import { createJp } from './instructions/control/jp.js';
import { createDi } from './instructions/control/di.js';
import { createLdSpD16 } from './instructions/load/ld-sp-d16.js';
import { createLdA16A } from './instructions/load/ld-a16-a.js';
import { createLdAD8 } from './instructions/load/ld-a-d8.js';
import { createLdhA8A } from './instructions/load/ldh-a8-a.js';
import { createLdHlD16 } from './instructions/load/ld-hl-d16.js';
import { createCall } from './instructions/control/call.js';
import { createLdAL } from './instructions/load/ld-a-l.js';
import { createLdAH } from './instructions/load/ld-a-h.js';
import { createJr } from './instructions/control/jr.js';
import { createPushHL } from './instructions/control/push-hl.js';
import { createPopHL } from './instructions/control/pop-hl.js';
import { createPushAF } from './instructions/control/push-af.js';
import { createIncHL } from './instructions/arithmetic/inc-hl.js';
import { createLdAHlInc } from './instructions/load/ld-a-hl-inc.js';
import { createPopAF } from './instructions/control/pop-af.js';
import { createPushBC } from './instructions/control/push-bc.js';
import { createLdBcD16 } from './instructions/load/ld-bc-d16.js';
import { createIncBC } from './instructions/arithmetic/inc-bc.js';
import { createLdAB } from './instructions/load/ld-a-b.js';
import { createOrC } from './instructions/arithmetic/or-c.js';
import { createJrZ } from './instructions/control/jr-z-r8.js';
import { createLdhA8 } from './instructions/load/ldh-a8.js';
import { createCpD8 } from './instructions/arithmetic/cp-d8.js';
import { createJrNz } from './instructions/control/jr-nz-r8.js';
import { createPopBc } from './instructions/control/pop-bc.js';
import { createLdAIndirectA16 } from './instructions/load/ld-a-indirect-a16.js';
import { createOrD8 } from './instructions/arithmetic/or-d8.js';
import { createCallNz } from './instructions/control/call-nz-a16.js';
import { createLdHlA } from './instructions/load/ld-hl-a.js';
import { createLdHLB } from './instructions/load/ld-hl-b.js';
import { createLdHLC } from './instructions/load/ld-hl-c.js';
import { createLdHLD } from './instructions/load/ld-hl-d.js';
import { createLdHLE } from './instructions/load/ld-hl-e.js';
import { createLdHLH } from './instructions/load/ld-hl-h.js';
import { createLdHLL } from './instructions/load/ld-hl-l.js';
import { createLdDeD16 } from './instructions/load/ld-de-d16.js';
import { createLdAIndirectDe } from './instructions/load/ld-a-indirect-de.js';
import { createLdAC } from './instructions/load/ld-a-c.js';
import { createLdAD } from './instructions/load/ld-a-d.js';
import { createLdAE } from './instructions/load/ld-a-e.js';
import { createLdAHLIndirect } from './instructions/load/ld-a-hl-indirect.js';
import { createLdAA } from './instructions/load/ld-a-a.js';
import { createLdHlIncA } from './instructions/load/ld-hl-inc-a.js';
import { createAddAD8 } from './instructions/arithmetic/add-a-d8.js';
import { createLdHlDecA } from './instructions/load/ld-hl-dec-a.js';
import { createSubD8 } from './instructions/arithmetic/sub-d8.js';
import { createSubB } from './instructions/arithmetic/sub-b.js';
import { createSubC } from './instructions/arithmetic/sub-c.js';
import { createSubD } from './instructions/arithmetic/sub-d.js';
import { createSubE } from './instructions/arithmetic/sub-e.js';
import { createSubH } from './instructions/arithmetic/sub-h.js';
import { createSubL } from './instructions/arithmetic/sub-l.js';
import { createSubHLIndirect } from './instructions/arithmetic/sub-hl-indirect.js';
import { createSubA } from './instructions/arithmetic/sub-a.js';
import { createOrB } from './instructions/arithmetic/or-b.js';
import { createOrD } from './instructions/arithmetic/or-d.js';
import { createOrE } from './instructions/arithmetic/or-e.js';
import { createOrH } from './instructions/arithmetic/or-h.js';
import { createOrL } from './instructions/arithmetic/or-l.js';
import { createOrHLIndirect } from './instructions/arithmetic/or-hl-indirect.js';
import { createOrA } from './instructions/arithmetic/or-a.js';
import { createPushDE } from './instructions/control/push-de.js';
import { createPopDE } from './instructions/control/pop-de.js';
import { createLdBB } from './instructions/load/ld-b-b.js';
import { createLdBC } from './instructions/load/ld-b-c.js';
import { createLdBD } from './instructions/load/ld-b-d.js';
import { createLdBE } from './instructions/load/ld-b-e.js';
import { createLdBH } from './instructions/load/ld-b-h.js';
import { createLdBL } from './instructions/load/ld-b-l.js';
import { createLdBHLIndirect } from './instructions/load/ld-b-hl-indirect.js';
import { createLdBA } from './instructions/load/ld-b-a.js';
import { createLdCB } from './instructions/load/ld-c-b.js';
import { createLdCC } from './instructions/load/ld-c-c.js';
import { createLdCD } from './instructions/load/ld-c-d.js';
import { createLdCE } from './instructions/load/ld-c-e.js';
import { createLdCH } from './instructions/load/ld-c-h.js';
import { createLdCL } from './instructions/load/ld-c-l.js';
import { createLdCHLIndirect } from './instructions/load/ld-c-hl-indirect.js';
import { createLdCA } from './instructions/load/ld-c-a.js';
import { createLdDB } from './instructions/load/ld-d-b.js';
import { createLdDC } from './instructions/load/ld-d-c.js';
import { createLdDD } from './instructions/load/ld-d-d.js';
import { createLdDE } from './instructions/load/ld-d-e.js';
import { createLdDH } from './instructions/load/ld-d-h.js';
import { createLdDL } from './instructions/load/ld-d-l.js';
import { createLdDHLIndirect } from './instructions/load/ld-d-hl-indirect.js';
import { createLdDA } from './instructions/load/ld-d-a.js';
import { createLdEB } from './instructions/load/ld-e-b.js';
import { createLdEC } from './instructions/load/ld-e-c.js';
import { createLdED } from './instructions/load/ld-e-d.js';
import { createLdEE } from './instructions/load/ld-e-e.js';
import { createLdEH } from './instructions/load/ld-e-h.js';
import { createLdEL } from './instructions/load/ld-e-l.js';
import { createLdEHLIndirect } from './instructions/load/ld-e-hl-indirect.js';
import { createLdEA } from './instructions/load/ld-e-a.js';
import { createLdHD8 } from './instructions/load/ld-h-d8.js';
import { createLdHB } from './instructions/load/ld-h-b.js';
import { createLdHC } from './instructions/load/ld-h-c.js';
import { createLdHD } from './instructions/load/ld-h-d.js';
import { createLdHE } from './instructions/load/ld-h-e.js';
import { createLdHH } from './instructions/load/ld-h-h.js';
import { createLdHL } from './instructions/load/ld-h-l.js';
import { createLdHHLIndirect } from './instructions/load/ld-h-hl-indirect.js';
import { createLdHA } from './instructions/load/ld-h-a.js';
import { createLdLB } from './instructions/load/ld-l-b.js';
import { createLdLC } from './instructions/load/ld-l-c.js';
import { createLdLD } from './instructions/load/ld-l-d.js';
import { createLdLE } from './instructions/load/ld-l-e.js';
import { createLdLH } from './instructions/load/ld-l-h.js';
import { createLdLL } from './instructions/load/ld-l-l.js';
import { createLdLHLIndirect } from './instructions/load/ld-l-hl-indirect.js';
import { createLdLA } from './instructions/load/ld-l-a.js';
import { createCbPrefix } from './instructions/control/cb-prefix.js';
import { createIncDE } from './instructions/arithmetic/inc-de.js';
import { createIncSP } from './instructions/arithmetic/inc-sp.js';
import { createXorB } from './instructions/arithmetic/xor-b.js';
import { createXorC } from './instructions/arithmetic/xor-c.js';
import { createXorD } from './instructions/arithmetic/xor-d.js';
import { createXorE } from './instructions/arithmetic/xor-e.js';
import { createXorH } from './instructions/arithmetic/xor-h.js';
import { createXorL } from './instructions/arithmetic/xor-l.js';
import { createXorHLIndirect } from './instructions/arithmetic/xor-hl-indirect.js';
import { createXorA } from './instructions/arithmetic/xor-a.js';
import { createAddAB } from './instructions/arithmetic/add-a-b.js';
import { createAddAC } from './instructions/arithmetic/add-a-c.js';
import { createAddAD } from './instructions/arithmetic/add-a-d.js';
import { createAddAE } from './instructions/arithmetic/add-a-e.js';
import { createAddAH } from './instructions/arithmetic/add-a-h.js';
import { createAddAL } from './instructions/arithmetic/add-a-l.js';
import { createAddAHLIndirect } from './instructions/arithmetic/add-a-hl-indirect.js';
import { createAddAA } from './instructions/arithmetic/add-a-a.js';
import { createAdcAB } from './instructions/arithmetic/adc-a-b.js';
import { createAdcAC } from './instructions/arithmetic/adc-a-c.js';
import { createAdcAD } from './instructions/arithmetic/adc-a-d.js';
import { createAdcAE } from './instructions/arithmetic/adc-a-e.js';
import { createAdcAH } from './instructions/arithmetic/adc-a-h.js';
import { createAdcAL } from './instructions/arithmetic/adc-a-l.js';
import { createAdcAHLIndirect } from './instructions/arithmetic/adc-a-hl-indirect.js';
import { createAdcAA } from './instructions/arithmetic/adc-a-a.js';
import { createSbcAB } from './instructions/arithmetic/sbc-a-b.js';
import { createSbcAC } from './instructions/arithmetic/sbc-a-c.js';
import { createSbcAD } from './instructions/arithmetic/sbc-a-d.js';
import { createSbcAE } from './instructions/arithmetic/sbc-a-e.js';
import { createSbcAH } from './instructions/arithmetic/sbc-a-h.js';
import { createSbcAL } from './instructions/arithmetic/sbc-a-l.js';
import { createSbcAHLIndirect } from './instructions/arithmetic/sbc-a-hl-indirect.js';
import { createSbcAA } from './instructions/arithmetic/sbc-a-a.js';
import { createAndB } from './instructions/arithmetic/and-b.js';
import { createAndC } from './instructions/arithmetic/and-c.js';
import { createAndD } from './instructions/arithmetic/and-d.js';
import { createAndE } from './instructions/arithmetic/and-e.js';
import { createAndH } from './instructions/arithmetic/and-h.js';
import { createAndL } from './instructions/arithmetic/and-l.js';
import { createAndHLIndirect } from './instructions/arithmetic/and-hl-indirect.js';
import { createAndA } from './instructions/arithmetic/and-a.js';

type Opcode = {
  mnemonic: string;
  bytes: number;
  execute: () => number;
};

type OpcodeTableDependencies = {
  mmu: MMU;
  registers: Registers;
};

const createOpcodeTable = ({
  mmu,
  registers,
}: OpcodeTableDependencies): Array<Opcode | undefined> => {

  const opcodes: Array<Opcode | undefined> = [];

  opcodes[0x00] = createNop({ registers });
  opcodes[0x01] = createLdBcD16({ mmu, registers });
  opcodes[0x03] = createIncBC({ registers });
  opcodes[0x13] = createIncDE({ registers });
  opcodes[0x33] = createIncSP({ registers });
  opcodes[0x06] = createLdBD8({ mmu, registers });
  opcodes[0x0e] = createLdCD8({ mmu, registers });
  opcodes[0x11] = createLdDeD16({ mmu, registers });
  opcodes[0x1a] = createLdAIndirectDe({ mmu, registers });
  opcodes[0x16] = createLdDD8({ mmu, registers });
  opcodes[0x20] = createJrNz({ mmu, registers });
  opcodes[0x21] = createLdHlD16({ mmu, registers });
  opcodes[0x26] = createLdHD8({ mmu, registers });
  opcodes[0x22] = createLdHlIncA({ mmu, registers });
  opcodes[0x23] = createIncHL({ registers });
  opcodes[0x28] = createJrZ({ mmu, registers });
  opcodes[0x31] = createLdSpD16({ mmu, registers });
  opcodes[0x32] = createLdHlDecA({ mmu, registers });
  opcodes[0x36] = createLdHLD8({ mmu, registers });
  opcodes[0x3e] = createLdAD8({ mmu, registers });
  opcodes[0xe0] = createLdhA8A({ mmu, registers });
  opcodes[0xea] = createLdA16A({ mmu, registers });
  opcodes[0x1e] = createLdED8({ mmu, registers });

  opcodes[0x3d] = createDecA({ registers });
  opcodes[0x04] = createIncB({ registers });
  opcodes[0x0c] = createIncC({ registers });
  opcodes[0x14] = createIncD({ registers });
  opcodes[0x18] = createJr({ mmu, registers });
  opcodes[0x1c] = createIncE({ registers });
  opcodes[0x24] = createIncH({ registers });
  opcodes[0x2a] = createLdAHlInc({ mmu, registers });
  opcodes[0x2c] = createIncL({ registers });
  opcodes[0x34] = createIncHLIndirect({ mmu, registers });
  opcodes[0x3c] = createIncA({ registers });

  opcodes[0x05] = createDecB({ registers });
  opcodes[0x0d] = createDecC({ registers });
  opcodes[0x15] = createDecD({ registers });
  opcodes[0x1d] = createDecE({ registers });
  opcodes[0x25] = createDecH({ registers });
  opcodes[0x2d] = createDecL({ registers });
  opcodes[0x35] = createDecHL({ mmu, registers });
  opcodes[0x70] = createLdHLB({ mmu, registers });
  opcodes[0x71] = createLdHLC({ mmu, registers });
  opcodes[0x72] = createLdHLD({ mmu, registers });
  opcodes[0x73] = createLdHLE({ mmu, registers });
  opcodes[0x74] = createLdHLH({ mmu, registers });
  opcodes[0x75] = createLdHLL({ mmu, registers });
  opcodes[0x77] = createLdHlA({ mmu, registers });
  opcodes[0x40] = createLdBB({ registers });
  opcodes[0x41] = createLdBC({ registers });
  opcodes[0x42] = createLdBD({ registers });
  opcodes[0x43] = createLdBE({ registers });
  opcodes[0x44] = createLdBH({ registers });
  opcodes[0x45] = createLdBL({ registers });
  opcodes[0x46] = createLdBHLIndirect({ mmu, registers });
  opcodes[0x47] = createLdBA({ registers });
  opcodes[0x48] = createLdCB({ registers });
  opcodes[0x49] = createLdCC({ registers });
  opcodes[0x4a] = createLdCD({ registers });
  opcodes[0x4b] = createLdCE({ registers });
  opcodes[0x4c] = createLdCH({ registers });
  opcodes[0x4d] = createLdCL({ registers });
  opcodes[0x4e] = createLdCHLIndirect({ mmu, registers });
  opcodes[0x4f] = createLdCA({ registers });
  opcodes[0x50] = createLdDB({ registers });
  opcodes[0x51] = createLdDC({ registers });
  opcodes[0x52] = createLdDD({ registers });
  opcodes[0x53] = createLdDE({ registers });
  opcodes[0x54] = createLdDH({ registers });
  opcodes[0x55] = createLdDL({ registers });
  opcodes[0x56] = createLdDHLIndirect({ mmu, registers });
  opcodes[0x57] = createLdDA({ registers });
  opcodes[0x58] = createLdEB({ registers });
  opcodes[0x59] = createLdEC({ registers });
  opcodes[0x5a] = createLdED({ registers });
  opcodes[0x5b] = createLdEE({ registers });
  opcodes[0x5c] = createLdEH({ registers });
  opcodes[0x5d] = createLdEL({ registers });
  opcodes[0x5e] = createLdEHLIndirect({ mmu, registers });
  opcodes[0x5f] = createLdEA({ registers });
  opcodes[0x60] = createLdHB({ registers });
  opcodes[0x61] = createLdHC({ registers });
  opcodes[0x62] = createLdHD({ registers });
  opcodes[0x63] = createLdHE({ registers });
  opcodes[0x64] = createLdHH({ registers });
  opcodes[0x65] = createLdHL({ registers });
  opcodes[0x66] = createLdHHLIndirect({ mmu, registers });
  opcodes[0x67] = createLdHA({ registers });
  opcodes[0x68] = createLdLB({ registers });
  opcodes[0x69] = createLdLC({ registers });
  opcodes[0x6a] = createLdLD({ registers });
  opcodes[0x6b] = createLdLE({ registers });
  opcodes[0x6c] = createLdLH({ registers });
  opcodes[0x6d] = createLdLL({ registers });
  opcodes[0x6e] = createLdLHLIndirect({ mmu, registers });
  opcodes[0x6f] = createLdLA({ registers });
  opcodes[0x78] = createLdAB({ registers });
  opcodes[0x79] = createLdAC({ registers });
  opcodes[0x7a] = createLdAD({ registers });
  opcodes[0x7b] = createLdAE({ registers });
  opcodes[0x7c] = createLdAH({ registers });
  opcodes[0x7d] = createLdAL({ registers });
  opcodes[0x7e] = createLdAHLIndirect({ mmu, registers });
  opcodes[0x7f] = createLdAA({ registers });
  opcodes[0x80] = createAddAB({ registers });
  opcodes[0x81] = createAddAC({ registers });
  opcodes[0x82] = createAddAD({ registers });
  opcodes[0x83] = createAddAE({ registers });
  opcodes[0x84] = createAddAH({ registers });
  opcodes[0x85] = createAddAL({ registers });
  opcodes[0x86] = createAddAHLIndirect({ mmu, registers });
  opcodes[0x87] = createAddAA({ registers });
  opcodes[0x88] = createAdcAB({ registers });
  opcodes[0x89] = createAdcAC({ registers });
  opcodes[0x8a] = createAdcAD({ registers });
  opcodes[0x8b] = createAdcAE({ registers });
  opcodes[0x8c] = createAdcAH({ registers });
  opcodes[0x8d] = createAdcAL({ registers });
  opcodes[0x8e] = createAdcAHLIndirect({ mmu, registers });
  opcodes[0x8f] = createAdcAA({ registers });
  opcodes[0x90] = createSubB({ registers });
  opcodes[0x91] = createSubC({ registers });
  opcodes[0x92] = createSubD({ registers });
  opcodes[0x93] = createSubE({ registers });
  opcodes[0x94] = createSubH({ registers });
  opcodes[0x95] = createSubL({ registers });
  opcodes[0x96] = createSubHLIndirect({ mmu, registers });
  opcodes[0x97] = createSubA({ registers });
  opcodes[0x98] = createSbcAB({ registers });
  opcodes[0x99] = createSbcAC({ registers });
  opcodes[0x9a] = createSbcAD({ registers });
  opcodes[0x9b] = createSbcAE({ registers });
  opcodes[0x9c] = createSbcAH({ registers });
  opcodes[0x9d] = createSbcAL({ registers });
  opcodes[0x9e] = createSbcAHLIndirect({ mmu, registers });
  opcodes[0x9f] = createSbcAA({ registers });
  opcodes[0xc6] = createAddAD8({ mmu, registers });
  opcodes[0xd6] = createSubD8({ mmu, registers });
  opcodes[0xa0] = createAndB({ registers });
  opcodes[0xa1] = createAndC({ registers });
  opcodes[0xa2] = createAndD({ registers });
  opcodes[0xa3] = createAndE({ registers });
  opcodes[0xa4] = createAndH({ registers });
  opcodes[0xa5] = createAndL({ registers });
  opcodes[0xa6] = createAndHLIndirect({ mmu, registers });
  opcodes[0xa7] = createAndA({ registers });
  opcodes[0xa8] = createXorB({ registers });
  opcodes[0xa9] = createXorC({ registers });
  opcodes[0xaa] = createXorD({ registers });
  opcodes[0xab] = createXorE({ registers });
  opcodes[0xac] = createXorH({ registers });
  opcodes[0xad] = createXorL({ registers });
  opcodes[0xae] = createXorHLIndirect({ mmu, registers });
  opcodes[0xaf] = createXorA({ registers });
  opcodes[0xb0] = createOrB({ registers });
  opcodes[0xb1] = createOrC({ registers });
  opcodes[0xb2] = createOrD({ registers });
  opcodes[0xb3] = createOrE({ registers });
  opcodes[0xb4] = createOrH({ registers });
  opcodes[0xb5] = createOrL({ registers });
  opcodes[0xb6] = createOrHLIndirect({ mmu, registers });
  opcodes[0xb7] = createOrA({ registers });
  opcodes[0xcb] = createCbPrefix({ mmu, registers });
  opcodes[0xc1] = createPopBc({ mmu, registers });
  opcodes[0xd1] = createPopDE({ mmu, registers });
  opcodes[0xd5] = createPushDE({ mmu, registers });
  opcodes[0xc3] = createJp({ mmu, registers });
  opcodes[0xc4] = createCallNz({ mmu, registers });
  opcodes[0xc5] = createPushBC({ mmu, registers });
  opcodes[0xc9] = createRet({ mmu, registers });
  opcodes[0xcd] = createCall({ mmu, registers });
  opcodes[0xe1] = createPopHL({ mmu, registers });
  opcodes[0xe5] = createPushHL({ mmu, registers });
  opcodes[0xe6] = createOrD8({ mmu, registers });
  opcodes[0xf0] = createLdhA8({ mmu, registers });
  opcodes[0xf1] = createPopAF({ mmu, registers });
  opcodes[0xf3] = createDi({ registers });
  opcodes[0xf5] = createPushAF({ mmu, registers });
  opcodes[0xfa] = createLdAIndirectA16({ mmu, registers });
  opcodes[0xfe] = createCpD8({ mmu, registers });
  return opcodes;
};

export { createOpcodeTable };
export type { Opcode };
